spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 412957065085-qnt4gscg8bls830k1l1rfu9i9hru5chk.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
              - profile
          github:
            clientId: a312195c4f28472f4f23
            clientSecret: 8b80e765fc7974099af2ab1e0cd3cb9218afdb6a
            redirectUri: "https://sead-usergroup3.herokuapp.com/login/oauth2/code/{registrationId}"
            scope:
              - user:email
              - read:user